# src/lang.py

LANGS = ["pt", "en", "es", "fr"]

# Idioma padrão ao iniciar o jogo
current_lang = "pt"

TEXTS = {
    "pt": {
        "title": "Dungeon Roguelike",
        "menu_start": "Iniciar",
        "menu_lang": "Idioma",
        "controls": "Controles:",
        "move_keys": "WASD ou Setas - Mover",
        "restart_key": "R - Recomeçar (após Game Over)",
        "quit_key": "Q ou ESC - Sair",
        "pause_key": "ESC (em jogo) - Pausar/Menu",
        "record": "Recorde",
        "paused": "Jogo Pausado",
        "resume": "Retomar",
        "game_over": "GAME OVER",
        "score": "Pontuação",
        "floor": "Andar",
        "life": "Vida",
        "coins": "Moedas",
        "highscore": "Recorde",
        "new_highscore": "Novo Recorde!",
        "medal_achieved": "Medalha conquistada!",
        "press_any_key": "Pressione qualquer tecla para começar...",
        "press_L_to_change": "Pressione L para trocar idioma",
        "challenge": "Desafio",
        "completed": "Concluído!",
        "failed": "Falhou",
        "medals": "Medalhas",
        "shop_first_coin": "Agora você pode abrir a loja apertando B!",
        "shop_menu_hint": "[B] Loja: Compre upgrades usando moedas durante o jogo.",

        # Desafios e Medalhas (KEYS!)
        "challenge_pacifista": "Zere o andar sem levar dano",
        "challenge_colecionador": "Pegue todos os tesouros do andar",
        "challenge_curador": "Pegue pelo menos uma cura antes de sair",
        "challenge_velocista": "Zere o andar em menos de 20 movimentos",
        "challenge_chaser": "Derrote um inimigo perseguidor",

        "medal_pacifista": "Pacifista",
        "desc_pacifista": "Zere um andar sem levar dano",
        "medal_colecionador": "Colecionador",
        "desc_colecionador": "Pegue todos os tesouros de um andar",
        "medal_sobrevivente": "Sobrevivente",
        "desc_sobrevivente": "Passe 3 andares sem perder vida",
        "medal_velocista": "Velocista",
        "desc_velocista": "Zere um andar em menos de 20 movimentos",
        "medal_invencivel": "Invencível",
        "desc_invencivel": "Chegue ao andar 10 sem morrer",
        "medal_curador": "Curador",
        "desc_curador": "Pegue 3 curas em um único andar",

        # HUD dinamico (formatáveis)
        "hud_life_now": "Vida atual: {0}",
        "hud_treasures": "{0}/{1} tesouros",
        "hud_heal_yes": "Pegou cura",
        "hud_not_yet": "Ainda não",
        "hud_moves": "{0}/20 movimentos",
        "hud_chaser_done": "Já derrotou"
    },
    "en": {
        "title": "Dungeon Roguelike",
        "menu_start": "Start",
        "menu_lang": "Language",
        "controls": "Controls:",
        "move_keys": "WASD or Arrows - Move",
        "restart_key": "R - Restart (after Game Over)",
        "quit_key": "Q or ESC - Quit",
        "pause_key": "ESC (in game) - Pause/Menu",
        "record": "Highscore",
        "paused": "Paused",
        "resume": "Resume",
        "game_over": "GAME OVER",
        "score": "Score",
        "floor": "Floor",
        "life": "Life",
        "coins": "Coins",
        "highscore": "Highscore",
        "new_highscore": "New Highscore!",
        "medal_achieved": "Medal Achieved!",
        "press_any_key": "Press any key to start...",
        "press_L_to_change": "Press L to change language",
        "challenge": "Challenge",
        "completed": "Completed!",
        "failed": "Failed",
        "medals": "Medals",
        "shop_first_coin": "Now you can open the shop by pressing B!",
        "shop_menu_hint": "[B] Shop: Buy upgrades using coins during the game.",

        # Challenges and Medals
        "challenge_pacifista": "Clear the floor without taking damage",
        "challenge_colecionador": "Collect all treasures on the floor",
        "challenge_curador": "Pick up at least one heal before exiting",
        "challenge_velocista": "Clear the floor in less than 20 moves",
        "challenge_chaser": "Defeat a chaser enemy",

        "medal_pacifista": "Pacifist",
        "desc_pacifista": "Clear a floor without taking damage",
        "medal_colecionador": "Collector",
        "desc_colecionador": "Collect all treasures on a floor",
        "medal_sobrevivente": "Survivor",
        "desc_sobrevivente": "Pass 3 floors without losing health",
        "medal_velocista": "Speedrunner",
        "desc_velocista": "Clear a floor in less than 20 moves",
        "medal_invencivel": "Invincible",
        "desc_invencivel": "Reach floor 10 without dying",
        "medal_curador": "Healer",
        "desc_curador": "Pick up 3 heals on a single floor",

        "hud_life_now": "Current life: {0}",
        "hud_treasures": "{0}/{1} treasures",
        "hud_heal_yes": "Healed",
        "hud_not_yet": "Not yet",
        "hud_moves": "{0}/20 moves",
        "hud_chaser_done": "Already defeated"
    },
    "es": {
        "title": "Dungeon Roguelike",
        "menu_start": "Iniciar",
        "menu_lang": "Idioma",
        "controls": "Controles:",
        "move_keys": "WASD o Flechas - Mover",
        "restart_key": "R - Reiniciar (tras Game Over)",
        "quit_key": "Q o ESC - Salir",
        "pause_key": "ESC (en juego) - Pausar/Menu",
        "record": "Récord",
        "paused": "Pausado",
        "resume": "Continuar",
        "game_over": "GAME OVER",
        "score": "Puntuación",
        "floor": "Piso",
        "life": "Vida",
        "coins": "Monedas",
        "highscore": "Récord",
        "new_highscore": "¡Nuevo Récord!",
        "medal_achieved": "¡Medalla conseguida!",
        "press_any_key": "Presiona cualquier tecla para comenzar...",
        "press_L_to_change": "Presiona L para cambiar idioma",
        "challenge": "Desafío",
        "completed": "¡Completado!",
        "failed": "Fallido",
        "medals": "Medallas",
        "shop_first_coin": "¡Ahora puedes abrir la tienda presionando B!",
        "shop_menu_hint": "[B] Tienda: Compra mejoras usando monedas durante el juego.",

        # Desafíos y medallas
        "challenge_pacifista": "Pasa el piso sin recibir daño",
        "challenge_colecionador": "Recoge todos los tesoros del piso",
        "challenge_curador": "Recoge al menos una cura antes de salir",
        "challenge_velocista": "Pasa el piso en menos de 20 movimientos",
        "challenge_chaser": "Derrota a un enemigo perseguidor",

        "medal_pacifista": "Pacifista",
        "desc_pacifista": "Pasa un piso sin recibir daño",
        "medal_colecionador": "Coleccionista",
        "desc_colecionador": "Recoge todos los tesoros de un piso",
        "medal_sobrevivente": "Sobreviviente",
        "desc_sobrevivente": "Pasa 3 pisos sin perder vida",
        "medal_velocista": "Velocista",
        "desc_velocista": "Pasa un piso en menos de 20 movimientos",
        "medal_invencivel": "Invencible",
        "desc_invencivel": "Llega al piso 10 sin morir",
        "medal_curador": "Sanador",
        "desc_curador": "Recoge 3 curas en un solo piso",

        "hud_life_now": "Vida actual: {0}",
        "hud_treasures": "{0}/{1} tesoros",
        "hud_heal_yes": "Curado",
        "hud_not_yet": "Aún no",
        "hud_moves": "{0}/20 movimientos",
        "hud_chaser_done": "Ya derrotado"
    },
    "fr": {
        "title": "Dungeon Roguelike",
        "menu_start": "Démarrer",
        "menu_lang": "Langue",
        "controls": "Contrôles:",
        "move_keys": "WASD ou Flèches - Bouger",
        "restart_key": "R - Recommencer (après Game Over)",
        "quit_key": "Q ou ESC - Quitter",
        "pause_key": "ESC (en jeu) - Pause/Menu",
        "record": "Record",
        "paused": "En pause",
        "resume": "Reprendre",
        "game_over": "GAME OVER",
        "score": "Score",
        "floor": "Étage",
        "life": "Vie",
        "coins": "Pièces",
        "highscore": "Record",
        "new_highscore": "Nouveau record !",
        "medal_achieved": "Médaille obtenue !",
        "press_any_key": "Appuyez sur une touche pour commencer...",
        "press_L_to_change": "Appuyez sur L pour changer de langue",
        "challenge": "Défi",
        "completed": "Terminé !",
        "failed": "Échoué",
        "medals": "Médailles",
        "shop_first_coin": "Vous pouvez maintenant ouvrir la boutique avec B !",
        "shop_menu_hint": "[B] Boutique : Achetez des améliorations avec vos pièces pendant le jeu.",

        # Défis et médailles
        "challenge_pacifista": "Terminez l'étage sans subir de dégâts",
        "challenge_colecionador": "Ramassez tous les trésors de l'étage",
        "challenge_curador": "Ramassez au moins une guérison avant de sortir",
        "challenge_velocista": "Terminez l'étage en moins de 20 mouvements",
        "challenge_chaser": "Vaincre un ennemi poursuivant",

        "medal_pacifista": "Pacifiste",
        "desc_pacifista": "Terminez un étage sans subir de dégâts",
        "medal_colecionador": "Collectionneur",
        "desc_colecionador": "Ramassez tous les trésors d'un étage",
        "medal_sobrevivente": "Survivant",
        "desc_sobrevivente": "Passez 3 étages sans perdre de vie",
        "medal_velocista": "Sprinteur",
        "desc_velocista": "Terminez un étage en moins de 20 mouvements",
        "medal_invencivel": "Invincible",
        "desc_invencivel": "Atteignez l'étage 10 sans mourir",
        "medal_curador": "Guérisseur",
        "desc_curador": "Ramassez 3 soins en un seul étage",

        "hud_life_now": "Vie actuelle : {0}",
        "hud_treasures": "{0}/{1} trésors",
        "hud_heal_yes": "Soigné",
        "hud_not_yet": "Pas encore",
        "hud_moves": "{0}/20 mouvements",
        "hud_chaser_done": "Déjà vaincu"
    }
}

def set_lang(lang):
    global current_lang
    if lang in LANGS:
        current_lang = lang

def _(key):
    return TEXTS[current_lang].get(key, key)
